"""fix ufdr foreign key

Revision ID: ac4775a7fe34
Revises: 67fc672f9a54
Create Date: 2025-10-07 00:10:00.084624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
# revision identifiers, used by Alembic.
revision: str = 'ac4775a7fe34'
down_revision: Union[str, Sequence[str], None] = '67fc672f9a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'ufdr_file_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('artifacts', 'extracted_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('artifacts', 'raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('artifacts', 'embedding')
    op.drop_constraint(op.f('ufdr_files_case_id_fkey'), 'ufdr_files', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('ufdr_files_case_id_fkey'), 'ufdr_files', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.add_column('artifacts', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True))
    op.alter_column('artifacts', 'raw',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('artifacts', 'extracted_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('artifacts', 'ufdr_file_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
